// Sidebar — autogenerated from the docs/ tree; cairn's folders and
// _category_.json files drive the shape.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  docs: [{ type: "autogenerated", dirName: "." }],
};
